#!/usr/bin/env python3
"""
Phase 45 - Generate rechecked_controls CSVs for 8 Azure services.

Services: addds, attestation, botservice, cloudshell,
          intelligentrecommendations, spatialanchors, trustedhardwareim, universalprint

Column order (exactly 10 cols):
  asb_control_id, feature_name, feature_supported_original,
  feature_enabled_by_default_original, status_2025, verdict_2025,
  azure_api_property, script_module, script_function, notes
"""

import csv
import os
import sys
from pathlib import Path

# ── output directory ──────────────────────────────────────────────────────────
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "outputs"
HEADER = [
    "asb_control_id",
    "feature_name",
    "feature_supported_original",
    "feature_enabled_by_default_original",
    "status_2025",
    "verdict_2025",
    "azure_api_property",
    "script_module",
    "script_function",
    "notes",
]

# ── service data ──────────────────────────────────────────────────────────────
# Each entry: (asb_control_id, feature_name, supported, enabled_default,
#              verdict_2025, azure_api_property, notes)
# status_2025 == verdict_2025 always
# script_module and script_function == "" always

ADDDS_ROWS = [
    (
        "IM-1",
        "Azure AD Authentication Required for Data Plane Access",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; ADDDS IS the Azure AD Domain Services identity provider — it is not a consumer of AAD auth; it provides Kerberos/LDAP for domain members; not_applicable at AAD DS service level",
    ),
    (
        "AM-5",
        "Microsoft Defender for Cloud - Adaptive Application Controls",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Adaptive Application Controls targets VMs; ADDDS is a PaaS managed domain service; not_applicable",
    ),
    (
        "IM-8",
        "Service Credential and Secrets Support Integration and Storage in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; ADDDS does not expose service credentials for Key Vault storage; fully Microsoft-managed; not_applicable",
    ),
    (
        "ES-2",
        "Anti-Malware Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; ADDDS is a PaaS managed service; underlying compute anti-malware is Microsoft-managed; not_applicable at ADDDS resource level",
    ),
    (
        "ES-3",
        "Anti-Malware Solution Health Monitoring",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; anti-malware health monitoring applies to customer-managed VMs; ADDDS PaaS service not applicable",
    ),
    (
        "PV-3",
        "Azure Automation State Configuration",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Automation DSC targets customer VMs; ADDDS managed nodes not configurable via customer Automation accounts; not_applicable",
    ),
    (
        "PV-6",
        "Azure Automation Update Management",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Update Management targets customer-owned VMs; ADDDS managed service patching is Microsoft-owned; not_applicable",
    ),
    (
        "BR-1",
        "Azure Backup",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; ADDDS does not use Azure Backup service; Microsoft-managed native backup covers domain state; not_applicable",
    ),
    (
        "PV-3",
        "Azure Policy Guest Configuration Agent",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Guest Configuration Agent targets customer VMs; ADDDS managed nodes not accessible for guest config; not_applicable",
    ),
    (
        "AM-2",
        "Azure Policy Support",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Azure Policy governance applies via tags and resource properties; customer cannot configure directly on the ADDDS PaaS control",
    ),
    (
        "PA-7",
        "Azure RBAC for Data Plane",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; ADDDS management plane uses ARM RBAC; data plane (domain join, LDAP queries) uses Kerberos/NTLM auth, not Azure RBAC; not_applicable",
    ),
    (
        "DP-7",
        "Certificate Management in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; ADDDS does not use Key Vault for certificate lifecycle management; LDAPS certificate is customer-provided but not Key Vault-managed; not_applicable",
    ),
    (
        "IM-7",
        "Conditional Access for Data Plane",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Conditional Access evaluates Entra ID sign-in; ADDDS data plane uses Kerberos/NTLM not Entra interactive auth; not_applicable",
    ),
    (
        "PA-8",
        "Customer Lockbox",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Customer Lockbox not supported for ADDDS; not_applicable",
    ),
    (
        "PV-3",
        "Custom Containers Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; ADDDS does not run customer container workloads; not_applicable",
    ),
    (
        "PV-3",
        "Custom VM Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; ADDDS domain controllers run Microsoft-managed images; customer cannot supply VM images; not_applicable",
    ),
    (
        "DP-5",
        "Data at Rest Encryption Using CMK",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; ADDDS does not support Customer-Managed Keys for data at rest; Microsoft-managed encryption only; not_applicable",
    ),
    (
        "DP-4",
        "Data at Rest Encryption Using Platform Keys",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: platform-enforced, enabled by default, not customer-configurable",
    ),
    (
        "DP-3",
        "Data in Transit Encryption",
        "True",
        "False",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: ADDDS enforces LDAPS (TCP 636) and Kerberos over TLS for data in transit; platform-configured; customers must configure LDAPS cert but TLS is enforced",
    ),
    (
        "DP-2",
        "Data Leakage/Loss Prevention",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; ADDDS does not support DLP controls at the service level; not_applicable",
    ),
    (
        "LT-1",
        "Microsoft Defender for Service / Product Offering",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; no Microsoft Defender plan for ADDDS as a service; Defender for Identity can monitor ADDDS-joined VMs but does not protect the ADDDS PaaS resource itself",
    ),
    (
        "NS-2",
        "Disable Public Network Access",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; ADDDS requires public IP for Azure portal management connectivity; no disable-public-access toggle; network access controlled via NSG on the ADDDS subnet",
    ),
    (
        "ES-1",
        "EDR Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; EDR applies to customer-managed endpoints/VMs; ADDDS managed nodes not customer-accessible; not_applicable",
    ),
    (
        "DP-6",
        "Key Management in Azure Key Vault",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; ADDDS does not integrate with Key Vault for key management; not_applicable",
    ),
    (
        "PA-1",
        "Local Admin Accounts",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; ADDDS managed service does not expose local admin accounts to customers; Microsoft manages the domain controller OS accounts; not_applicable",
    ),
    (
        "IM-1",
        "Local Authentication Methods for Data Plane Access",
        "True",
        "False",
        "implemented",
        "N/A — LIVE→UNKNOWN (no ARM property)",
        "LIVE→UNKNOWN: ADDDS supports Kerberos and NTLM local auth methods; NTLM can be restricted via fine-grained password policy but no ARM property to inspect remotely; verify via Azure Policy audit",
    ),
    (
        "IM-3",
        "Managed Identities",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; ADDDS does not support Managed Identity assignment; it is the identity provider, not a consumer of managed identity; not_applicable",
    ),
    (
        "BR-1",
        "Service Native Backup Capability",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: ADDDS managed service backup is platform-enforced; frequency determined by SKU (hourly/daily); customer cannot configure",
    ),
    (
        "NS-1",
        "Network Security Group Support",
        "True",
        "False",
        "implemented",
        "subnet(aadds-subnet).network_security_group",
        "LIVE-DIRECT: NSG required on ADDDS dedicated subnet; NSG existence confirms compliance; do not validate individual rules (Microsoft-required rules are auto-applied)",
    ),
    (
        "NS-2",
        "Azure Private Link",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; ADDDS is not a Private Link-capable service; it requires dedicated subnet within customer VNet",
    ),
    (
        "LT-4",
        "Azure Resource Logs",
        "True",
        "False",
        "implemented",
        "DiagnosticSettings(domainService.id).logs",
        "LIVE-DIRECT: ADDDS emits security audit logs (Kerberos auth, NTLM auth, LDAP bind); check DiagnosticSettings for log category enabled",
    ),
    (
        "DP-1",
        "Sensitive Data Discovery and Classification",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; ADDDS does not support data discovery or classification; not_applicable",
    ),
    (
        "IM-3",
        "Service Principals",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; ADDDS does not support Service Principal authentication; management plane uses ARM RBAC; not_applicable",
    ),
    (
        "NS-1",
        "Virtual Network Integration",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: ADDDS deploys into a dedicated subnet in customer VNet; VNet integration is required and platform-enforced",
    ),
    (
        "PV-5",
        "Vulnerability Assessment using Microsoft Defender",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Vulnerability Assessment targets customer VMs; ADDDS PaaS service not applicable",
    ),
]

ATTESTATION_ROWS = [
    (
        "IM-1",
        "Azure AD Authentication Required for Data Plane Access",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: platform-enforced, enabled by default, not customer-configurable",
    ),
    (
        "AM-5",
        "Microsoft Defender for Cloud - Adaptive Application Controls",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Adaptive Application Controls targets VMs; Azure Attestation is a PaaS service; not_applicable",
    ),
    (
        "IM-8",
        "Service Credential and Secrets Support Integration and Storage in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Attestation uses token-based AAD auth; no service credentials requiring Key Vault storage; not_applicable",
    ),
    (
        "ES-2",
        "Anti-Malware Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Attestation is PaaS; underlying compute anti-malware is Microsoft-managed; not_applicable",
    ),
    (
        "ES-3",
        "Anti-Malware Solution Health Monitoring",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; anti-malware health monitoring targets customer VMs; PaaS service not applicable",
    ),
    (
        "PV-3",
        "Azure Automation State Configuration",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Automation DSC targets customer VMs; PaaS attestation service not applicable",
    ),
    (
        "PV-6",
        "Azure Automation Update Management",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Update Management targets customer-owned VMs; PaaS attestation service not applicable",
    ),
    (
        "BR-1",
        "Azure Backup",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Attestation is a stateless PaaS service with no customer data requiring backup; not_applicable",
    ),
    (
        "PV-3",
        "Azure Policy Guest Configuration Agent",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Guest Configuration targets VMs; PaaS attestation service not applicable",
    ),
    (
        "AM-2",
        "Azure Policy Support",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: platform-enforced, enabled by default, not customer-configurable",
    ),
    (
        "PA-7",
        "Azure RBAC for Data Plane",
        "True",
        "False",
        "implemented",
        "Microsoft.Attestation/attestationProviders/*/read (RBAC assignment)",
        "LIVE-DIRECT: Azure RBAC controls who can create/manage attestation providers; check RBAC assignments on resource; Attestation Contributor/Reader built-in roles",
    ),
    (
        "DP-7",
        "Certificate Management in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Attestation does not manage certificates via Key Vault; attestation uses signed tokens; not_applicable",
    ),
    (
        "IM-7",
        "Conditional Access for Data Plane",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Conditional Access evaluates Entra ID sign-in context; MAA attestation API uses token-based auth not subject to CA policy directly; not_applicable",
    ),
    (
        "PA-8",
        "Customer Lockbox",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Customer Lockbox is supported for Azure Attestation; platform-enforced approval workflow for Microsoft support access",
    ),
    (
        "PV-3",
        "Custom Containers Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Attestation does not run customer container workloads; not_applicable",
    ),
    (
        "PV-3",
        "Custom VM Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Attestation PaaS service does not expose VM image customization; not_applicable",
    ),
    (
        "DP-5",
        "Data at Rest Encryption Using CMK",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Azure Attestation is stateless; no persistent customer data at rest requiring CMK; not_applicable",
    ),
    (
        "DP-4",
        "Data at Rest Encryption Using Platform Keys",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: platform-enforced, enabled by default, not customer-configurable",
    ),
    (
        "DP-3",
        "Data in Transit Encryption",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: platform-enforced, enabled by default, not customer-configurable",
    ),
    (
        "DP-2",
        "Data Leakage/Loss Prevention",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Azure Attestation is stateless; no persistent customer data requiring DLP; not_applicable",
    ),
    (
        "LT-1",
        "Microsoft Defender for Service / Product Offering",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; no Microsoft Defender plan exists for Azure Attestation as a service; not_applicable",
    ),
    (
        "NS-2",
        "Disable Public Network Access",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Public network access can be disabled on attestation provider; platform enforces when set",
    ),
    (
        "ES-1",
        "EDR Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; EDR targets customer-managed endpoints; PaaS attestation service not applicable",
    ),
    (
        "DP-6",
        "Key Management in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Attestation does not use Key Vault for key management; not_applicable",
    ),
    (
        "PA-1",
        "Local Admin Accounts",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Attestation PaaS service has no customer-accessible local admin accounts; not_applicable",
    ),
    (
        "IM-1",
        "Local Authentication Methods for Data Plane Access",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Attestation requires AAD token auth; no local auth methods supported; not_applicable",
    ),
    (
        "IM-3",
        "Managed Identities",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Managed Identity supported for attestation requests; system-assigned MI can authenticate to MAA endpoint",
    ),
    (
        "BR-1",
        "Service Native Backup Capability",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Attestation is stateless; no customer data to back up; not_applicable",
    ),
    (
        "NS-1",
        "Network Security Group Support",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Azure Attestation does not deploy into customer VNet; no NSG support; not_applicable",
    ),
    (
        "NS-2",
        "Azure Private Link",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Private endpoint support for Azure Attestation GA; platform-enforced when enabled; blocks public attestation endpoint",
    ),
    (
        "LT-4",
        "Azure Resource Logs",
        "True",
        "False",
        "implemented",
        "DiagnosticSettings(attestationProvider.id).logs",
        "LIVE-DIRECT: Azure Attestation emits audit logs via Diagnostic Settings; check AuditEvent log category enabled",
    ),
    (
        "DP-1",
        "Sensitive Data Discovery and Classification",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Azure Attestation is stateless; no persistent data for discovery/classification; not_applicable",
    ),
    (
        "IM-3",
        "Service Principals",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Service Principals supported for attestation API calls; standard AAD app registration pattern",
    ),
    (
        "NS-1",
        "Virtual Network Integration",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Azure Attestation does not support VNet integration; uses Private Link for network isolation; not_applicable",
    ),
    (
        "PV-5",
        "Vulnerability Assessment using Microsoft Defender",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Vulnerability Assessment targets customer VMs; PaaS attestation service not applicable",
    ),
]

BOTSERVICE_ROWS = [
    (
        "IM-1",
        "Azure AD Authentication Required for Data Plane Access",
        "True",
        "False",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Azure Bot Service enforces AAD authentication for management plane; data plane channel auth uses AAD tokens",
    ),
    (
        "AM-5",
        "Microsoft Defender for Cloud - Adaptive Application Controls",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Adaptive Application Controls targets VMs; Bot Service is PaaS; not_applicable",
    ),
    (
        "IM-8",
        "Service Credential and Secrets Support Integration and Storage in Azure Key Vault",
        "True",
        "False",
        "implemented",
        "N/A — LIVE→UNKNOWN (no ARM property)",
        "LIVE→UNKNOWN: Bot Service credentials (MSA app secret) can be stored in Key Vault; no ARM property on bot resource to verify KV usage; behavioral pattern",
    ),
    (
        "ES-2",
        "Anti-Malware Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Bot Service is a PaaS messaging gateway; anti-malware not applicable at service resource level",
    ),
    (
        "ES-3",
        "Anti-Malware Solution Health Monitoring",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; anti-malware health monitoring targets customer VMs; PaaS Bot Service not applicable",
    ),
    (
        "PV-3",
        "Azure Automation State Configuration",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Automation DSC targets customer VMs; PaaS Bot Service not applicable",
    ),
    (
        "PV-6",
        "Azure Automation Update Management",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Update Management targets customer VMs; PaaS Bot Service not applicable",
    ),
    (
        "BR-1",
        "Azure Backup",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Bot Service configuration does not use Azure Backup; configuration is in ARM templates; not_applicable",
    ),
    (
        "PV-3",
        "Azure Policy Guest Configuration Agent",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Guest Configuration targets VMs; PaaS Bot Service not applicable",
    ),
    (
        "AM-2",
        "Azure Policy Support",
        "True",
        "False",
        "implemented",
        "botService.tags",
        "LIVE-DIRECT: tags proxy for Azure Policy governance; botService.tags non-empty → PASS",
    ),
    (
        "PA-7",
        "Azure RBAC for Data Plane",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Azure RBAC applies to management plane (create/delete bot); data plane (message delivery) does not support Azure RBAC; not_applicable",
    ),
    (
        "DP-7",
        "Certificate Management in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Bot Service does not use Key Vault for certificate management; not_applicable",
    ),
    (
        "IM-7",
        "Conditional Access for Data Plane",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Conditional Access evaluates Entra ID sign-in sessions; Bot Service data plane (messaging API) uses token auth not evaluated by CA policy; not_applicable",
    ),
    (
        "PA-8",
        "Customer Lockbox",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Bot Service not in Customer Lockbox supported service list; not_applicable",
    ),
    (
        "PV-3",
        "Custom Containers Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Bot Service does not run customer container images at the bot resource level; not_applicable",
    ),
    (
        "PV-3",
        "Custom VM Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Bot Service PaaS does not support custom VM images; not_applicable",
    ),
    (
        "DP-5",
        "Data at Rest Encryption Using CMK",
        "True",
        "False",
        "implemented",
        "N/A — LIVE→UNKNOWN (no ARM property)",
        "LIVE→UNKNOWN: Bot Service supports CMK via customer-managed key in Key Vault; no ARM property directly on bot resource to verify; check Key Vault integration",
    ),
    (
        "DP-4",
        "Data at Rest Encryption Using Platform Keys",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: platform-enforced, enabled by default, not customer-configurable",
    ),
    (
        "DP-3",
        "Data in Transit Encryption",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: platform-enforced, enabled by default, not customer-configurable",
    ),
    (
        "DP-2",
        "Data Leakage/Loss Prevention",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Bot Service does not support DLP at the service level; not_applicable",
    ),
    (
        "LT-1",
        "Microsoft Defender for Service / Product Offering",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; no Microsoft Defender plan for Bot Service as a service resource; Defender for App Service covers the underlying App Service hosting the bot; not_applicable at Bot resource level",
    ),
    (
        "NS-2",
        "Disable Public Network Access",
        "True",
        "False",
        "implemented",
        "botService.properties.publicNetworkAccess",
        "LIVE-DIRECT: check properties.publicNetworkAccess == Disabled",
    ),
    (
        "ES-1",
        "EDR Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; EDR targets customer-managed endpoints; PaaS Bot Service not applicable",
    ),
    (
        "DP-6",
        "Key Management in Azure Key Vault",
        "True",
        "False",
        "implemented",
        "N/A — LIVE→UNKNOWN (no ARM property)",
        "LIVE→UNKNOWN: Bot Service can use Key Vault for key management; no ARM property on bot resource to verify; behavioral pattern",
    ),
    (
        "PA-1",
        "Local Admin Accounts",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Bot Service PaaS does not expose local admin accounts; not_applicable",
    ),
    (
        "IM-1",
        "Local Authentication Methods for Data Plane Access",
        "True",
        "False",
        "implemented",
        "N/A — LIVE→UNKNOWN",
        "LIVE→UNKNOWN: Bot Service supports local auth methods (MSA password); customers should prefer MI over passwords; no ARM property to verify local auth disabled",
    ),
    (
        "IM-3",
        "Managed Identities",
        "True",
        "False",
        "implemented",
        "botService.properties.msaAppMSIResourceId",
        "LIVE-DIRECT: Bot Service supports system-assigned MI for downstream service calls; check identity.type == SystemAssigned",
    ),
    (
        "BR-1",
        "Service Native Backup Capability",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Bot Service configuration is declarative; no native backup capability; not_applicable",
    ),
    (
        "NS-1",
        "Network Security Group Support",
        "True",
        "False",
        "implemented",
        "botService.properties.endpoint",
        "LIVE-DIRECT: Bot Service can be deployed with VNet integration; NSG governs traffic; check if privateEndpointConnections present or endpoint is internal",
    ),
    (
        "NS-2",
        "Azure Private Link",
        "True",
        "False",
        "implemented",
        "botService.properties.privateEndpointConnections",
        "LIVE-DIRECT: Bot Service supports private endpoints via Direct Line App Service extension; check privateEndpointConnections length > 0",
    ),
    (
        "LT-4",
        "Azure Resource Logs",
        "True",
        "False",
        "implemented",
        "DiagnosticSettings(botService.id).logs",
        "LIVE-DIRECT: Bot Service emits BotRequest diagnostic logs; check DiagnosticSettings for BotRequest category enabled",
    ),
    (
        "DP-1",
        "Sensitive Data Discovery and Classification",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Bot Service does not support data discovery or classification; not_applicable",
    ),
    (
        "IM-3",
        "Service Principals",
        "True",
        "False",
        "implemented",
        "botService.properties.msaAppId",
        "LIVE-DIRECT: Bot Service authenticates via SP (MSA App ID); check properties.msaAppId is set and not empty",
    ),
    (
        "NS-1",
        "Virtual Network Integration",
        "True",
        "False",
        "implemented",
        "botService.properties.endpoint",
        "LIVE-DIRECT: Bot Service supports VNet integration via App Service hosting; check endpoint is internal or private endpoint exists",
    ),
    (
        "PV-5",
        "Vulnerability Assessment using Microsoft Defender",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Vulnerability Assessment targets customer VMs; PaaS Bot Service not applicable",
    ),
]

CLOUDSHELL_ROWS = [
    (
        "IM-1",
        "Azure AD Authentication Required for Data Plane Access",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell is a browser-based terminal accessed via Azure portal; portal session validates Entra ID identity before Cloud Shell is launched; Cloud Shell itself does not independently authenticate users; not_applicable at Cloud Shell resource level",
    ),
    (
        "AM-5",
        "Microsoft Defender for Cloud - Adaptive Application Controls",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Adaptive Application Controls targets customer VMs; Cloud Shell ephemeral compute is Microsoft-managed; not_applicable",
    ),
    (
        "IM-8",
        "Service Credential and Secrets Support Integration and Storage in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell does not manage service credentials; users can call Key Vault from within a shell session; not_applicable at Cloud Shell service level",
    ),
    (
        "ES-2",
        "Anti-Malware Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell ephemeral containers are Microsoft-managed; anti-malware not customer-configurable; not_applicable",
    ),
    (
        "ES-3",
        "Anti-Malware Solution Health Monitoring",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; anti-malware health monitoring targets customer VMs; Cloud Shell ephemeral compute not applicable",
    ),
    (
        "PV-3",
        "Azure Automation State Configuration",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Automation DSC targets customer VMs; Cloud Shell ephemeral containers not applicable",
    ),
    (
        "PV-6",
        "Azure Automation Update Management",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Update Management targets customer VMs; Cloud Shell ephemeral compute is Microsoft-managed; not_applicable",
    ),
    (
        "BR-1",
        "Azure Backup",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell session state is persisted in customer-owned Azure Storage; backup is responsibility of that storage account; not_applicable at Cloud Shell service level",
    ),
    (
        "PV-3",
        "Azure Policy Guest Configuration Agent",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Guest Configuration targets customer VMs; Cloud Shell ephemeral containers not applicable",
    ),
    (
        "AM-2",
        "Azure Policy Support",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Cloud Shell does not support Azure Policy assignment directly; no taggable resource in standard deployment; not_applicable",
    ),
    (
        "PA-7",
        "Azure RBAC for Data Plane",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell data plane is a terminal session; Azure RBAC does not control terminal operations; not_applicable",
    ),
    (
        "DP-7",
        "Certificate Management in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell does not manage certificates; users can interact with Key Vault from a shell session; not_applicable at service level",
    ),
    (
        "IM-7",
        "Conditional Access for Data Plane",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Conditional Access governs the Azure portal sign-in that launches Cloud Shell; Cloud Shell data plane session not separately CA-evaluated; not_applicable",
    ),
    (
        "PA-8",
        "Customer Lockbox",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell is not in the Customer Lockbox supported service list; not_applicable",
    ),
    (
        "PV-3",
        "Custom Containers Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell uses Microsoft-managed container images; not_applicable",
    ),
    (
        "PV-3",
        "Custom VM Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell ephemeral compute uses Microsoft-managed images; not_applicable",
    ),
    (
        "DP-5",
        "Data at Rest Encryption Using CMK",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; CMK applies to the customer's linked Azure Storage account (where Cloud Shell persists $HOME); configure CMK on storage, not on Cloud Shell resource; not_applicable at Cloud Shell service level",
    ),
    (
        "DP-4",
        "Data at Rest Encryption Using Platform Keys",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell stores session data in customer-owned Azure Storage account; data encryption is controlled by the storage account not by Cloud Shell; not_applicable at Cloud Shell service level",
    ),
    (
        "DP-3",
        "Data in Transit Encryption",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Cloud Shell enforces HTTPS/TLS for all browser-to-session traffic; platform-enforced; not customer-configurable",
    ),
    (
        "DP-2",
        "Data Leakage/Loss Prevention",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell session data is owned by customer in their linked Azure Storage file share; DLP applies to that storage account; not_applicable at Cloud Shell service level",
    ),
    (
        "LT-1",
        "Microsoft Defender for Service / Product Offering",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; no Defender plan for Cloud Shell as a service; Defender covers the underlying compute but not the Cloud Shell session service; not_applicable",
    ),
    (
        "NS-2",
        "Disable Public Network Access",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Cloud Shell requires internet connectivity for portal access; no disable-public-access toggle; VNet injection (NS-1) is the isolation alternative; not_applicable",
    ),
    (
        "ES-1",
        "EDR Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; EDR targets customer-managed endpoints; Cloud Shell ephemeral compute is Microsoft-managed; not_applicable",
    ),
    (
        "DP-6",
        "Key Management in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell does not use Key Vault for key management; users may use Key Vault from within a shell session; not_applicable at service level",
    ),
    (
        "PA-1",
        "Local Admin Accounts",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell runs as the portal user context; no local admin account concept; not_applicable",
    ),
    (
        "IM-1",
        "Local Authentication Methods for Data Plane Access",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell access is gated by Azure portal Entra ID session; no local auth methods for Cloud Shell itself; not_applicable",
    ),
    (
        "IM-3",
        "Managed Identities",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell does not support assigning Managed Identity to the Cloud Shell service itself; users can use MI from within a shell script; not_applicable at Cloud Shell resource level",
    ),
    (
        "BR-1",
        "Service Native Backup Capability",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell has no native backup; data persisted in customer-owned Azure Storage; not_applicable at Cloud Shell service level",
    ),
    (
        "NS-1",
        "Network Security Group Support",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; standard Cloud Shell has no customer VNet; NSG not applicable in standard mode; VNet injection mode (NS-1 VNet Integration) is required for isolation; not_applicable",
    ),
    (
        "NS-2",
        "Azure Private Link",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Cloud Shell does not support Private Link; VNet injection provides network isolation; not_applicable",
    ),
    (
        "LT-4",
        "Azure Resource Logs",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Cloud Shell does not emit Azure Monitor resource diagnostic logs; session activity is terminal I/O only; not_applicable",
    ),
    (
        "DP-1",
        "Sensitive Data Discovery and Classification",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Cloud Shell does not support data discovery or classification; not_applicable",
    ),
    (
        "IM-3",
        "Service Principals",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Cloud Shell does not support Service Principal assignment to the service; users can authenticate as SP from within a shell session; not_applicable at service level",
    ),
    (
        "NS-1",
        "Virtual Network Integration",
        "True",
        "False",
        "implemented",
        "cloudShell.properties.networkProfile.subnetId",
        "LIVE-DIRECT: Cloud Shell supports VNet injection (isolated mode) via linked storage and VNet configuration; check networkProfile.subnetId is set",
    ),
    (
        "PV-5",
        "Vulnerability Assessment using Microsoft Defender",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Vulnerability Assessment targets customer VMs; Cloud Shell ephemeral compute is Microsoft-managed; not_applicable",
    ),
]

INTELLIGENTRECOMMENDATIONS_ROWS = [
    (
        "IM-1",
        "Azure AD Authentication Required for Data Plane Access",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Azure Intelligent Recommendations enforces Entra ID authentication for API access; AAD token required for all data plane calls",
    ),
    (
        "IM-1",
        "Azure AD Authentication Required for Data Plane Access",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Azure Intelligent Recommendations enforces Entra ID authentication for API access; AAD token required for all data plane calls",
    ),
    (
        "AM-5",
        "Microsoft Defender for Cloud - Adaptive Application Controls",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Adaptive Application Controls targets VMs; Intelligent Recommendations is PaaS; not_applicable",
    ),
    (
        "IM-8",
        "Service Credential and Secrets Support Integration and Storage in Azure Key Vault",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations uses AAD token auth; no service credentials requiring Key Vault storage; not_applicable",
    ),
    (
        "ES-2",
        "Anti-Malware Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Intelligent Recommendations is a PaaS service; underlying compute anti-malware is Microsoft-managed; not_applicable",
    ),
    (
        "ES-3",
        "Anti-Malware Solution Health Monitoring",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; anti-malware health monitoring targets customer VMs; PaaS service not applicable",
    ),
    (
        "PV-3",
        "Azure Automation State Configuration",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Automation DSC targets customer VMs; PaaS Intelligent Recommendations service not applicable",
    ),
    (
        "PV-6",
        "Azure Automation Update Management",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Update Management targets customer VMs; PaaS service not applicable",
    ),
    (
        "BR-1",
        "Azure Backup",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations does not use Azure Backup; not_applicable",
    ),
    (
        "PV-3",
        "Azure Policy Guest Configuration Agent",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Guest Configuration targets VMs; PaaS service not applicable",
    ),
    (
        "AM-2",
        "Azure Policy Support",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations does not support Azure Policy assignment; not_applicable",
    ),
    (
        "PA-7",
        "Azure RBAC for Data Plane",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations does not support Azure RBAC for data plane access; not_applicable",
    ),
    (
        "DP-7",
        "Certificate Management in Azure Key Vault",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations does not use Key Vault for certificate management; not_applicable",
    ),
    (
        "IM-7",
        "Conditional Access for Data Plane",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Conditional Access evaluates Entra ID sign-in; Intelligent Recommendations API uses token auth; not_applicable",
    ),
    (
        "PA-8",
        "Customer Lockbox",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations not in Customer Lockbox supported service list; not_applicable",
    ),
    (
        "PV-3",
        "Custom Containers Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Intelligent Recommendations does not run customer container workloads; not_applicable",
    ),
    (
        "PV-3",
        "Custom VM Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Intelligent Recommendations PaaS does not expose VM image customization; not_applicable",
    ),
    (
        "DP-5",
        "Data at Rest Encryption Using CMK",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations does not support CMK; Microsoft-managed encryption only; not_applicable",
    ),
    (
        "DP-4",
        "Data at Rest Encryption Using Platform Keys",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Customer content at rest encrypted with Microsoft-managed keys by default; platform-enforced",
    ),
    (
        "DP-3",
        "Data in Transit Encryption",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: TLS 1.2 enforced for all API traffic; platform-enforced",
    ),
    (
        "DP-2",
        "Data Leakage/Loss Prevention",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations does not support DLP controls; not_applicable",
    ),
    (
        "LT-1",
        "Microsoft Defender for Service / Product Offering",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; no Microsoft Defender plan for Intelligent Recommendations; not_applicable",
    ),
    (
        "NS-2",
        "Disable Public Network Access",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations does not support disabling public network access; not_applicable",
    ),
    (
        "ES-1",
        "EDR Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; EDR targets customer-managed endpoints; PaaS service not applicable",
    ),
    (
        "DP-6",
        "Key Management in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Intelligent Recommendations does not use Key Vault for key management; not_applicable",
    ),
    (
        "PA-1",
        "Local Admin Accounts",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations PaaS does not expose local admin accounts; not_applicable",
    ),
    (
        "IM-1",
        "Local Authentication Methods for Data Plane Access",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations requires AAD auth; local authentication methods not supported; not_applicable",
    ),
    (
        "IM-3",
        "Managed Identities",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations does not support Managed Identity assignment; not_applicable",
    ),
    (
        "BR-1",
        "Service Native Backup Capability",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations does not support native backup; not_applicable",
    ),
    (
        "NS-1",
        "Network Security Group Support",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations does not support VNet/NSG integration; not_applicable",
    ),
    (
        "NS-2",
        "Azure Private Link",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations does not support Private Link; not_applicable",
    ),
    (
        "LT-4",
        "Azure Resource Logs",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False in MCSB v3 baseline; Azure Intelligent Recommendations does not support Azure Monitor resource logs; operational telemetry limited to metrics; not_applicable",
    ),
    (
        "LT-4",
        "Azure Resource Logs",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False in MCSB v3 baseline; Azure Intelligent Recommendations does not support Azure Monitor resource logs; operational telemetry limited to metrics; not_applicable",
    ),
    (
        "DP-1",
        "Sensitive Data Discovery and Classification",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations does not support data discovery or classification; not_applicable",
    ),
    (
        "IM-3",
        "Service Principals",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Service Principals supported for Intelligent Recommendations API authentication; standard AAD app-registration pattern",
    ),
    (
        "IM-3",
        "Service Principals",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Service Principals supported for Intelligent Recommendations API authentication; standard AAD app-registration pattern",
    ),
    (
        "NS-1",
        "Virtual Network Integration",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Intelligent Recommendations does not support VNet integration; not_applicable",
    ),
    (
        "PV-5",
        "Vulnerability Assessment using Microsoft Defender",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Vulnerability Assessment targets customer VMs; PaaS service not applicable",
    ),
]

SPATIALANCHORS_ROWS = [
    (
        "IM-1",
        "Azure AD Authentication Required for Data Plane Access",
        "True",
        "False",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Azure Spatial Anchors enforces AAD auth for anchor management API (create/read/update/delete); deprecated November 2024",
    ),
    (
        "AM-5",
        "Microsoft Defender for Cloud - Adaptive Application Controls",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Adaptive Application Controls targets VMs; Spatial Anchors is PaaS; deprecated November 2024; not_applicable",
    ),
    (
        "IM-8",
        "Service Credential and Secrets Support Integration and Storage in Azure Key Vault",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Spatial Anchors uses AAD token auth; no service credentials requiring Key Vault storage; deprecated November 2024; not_applicable",
    ),
    (
        "ES-2",
        "Anti-Malware Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Spatial Anchors is PaaS; anti-malware not applicable at service level; deprecated November 2024; not_applicable",
    ),
    (
        "ES-3",
        "Anti-Malware Solution Health Monitoring",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; anti-malware health monitoring targets customer VMs; PaaS service not applicable; deprecated November 2024; not_applicable",
    ),
    (
        "PV-3",
        "Azure Automation State Configuration",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Automation DSC targets customer VMs; PaaS Spatial Anchors service not applicable; deprecated November 2024; not_applicable",
    ),
    (
        "PV-6",
        "Azure Automation Update Management",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Update Management targets customer VMs; PaaS service not applicable; deprecated November 2024; not_applicable",
    ),
    (
        "BR-1",
        "Azure Backup",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Spatial Anchors does not use Azure Backup; deprecated November 2024; not_applicable",
    ),
    (
        "PV-3",
        "Azure Policy Guest Configuration Agent",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Guest Configuration targets VMs; PaaS service not applicable; deprecated November 2024; not_applicable",
    ),
    (
        "AM-2",
        "Azure Policy Support",
        "True",
        "False",
        "implemented",
        "spatialAnchorsAccount.tags",
        "LIVE-DIRECT: tags proxy for Azure Policy governance; deprecated November 2024",
    ),
    (
        "PA-7",
        "Azure RBAC for Data Plane",
        "True",
        "False",
        "implemented",
        "Microsoft.MixedReality/spatialAnchorsAccounts/*/read (RBAC assignment)",
        "LIVE-DIRECT: Azure RBAC controls anchor account access; Spatial Anchors Account Owner/Contributor built-in roles; deprecated November 2024",
    ),
    (
        "DP-7",
        "Certificate Management in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Spatial Anchors does not use Key Vault for certificate management; deprecated November 2024; not_applicable",
    ),
    (
        "IM-7",
        "Conditional Access for Data Plane",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Conditional Access evaluates Entra ID sign-in; Spatial Anchors API token auth not directly CA-evaluated; deprecated November 2024; not_applicable",
    ),
    (
        "PA-8",
        "Customer Lockbox",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Spatial Anchors not in Customer Lockbox supported service list; deprecated November 2024; not_applicable",
    ),
    (
        "PV-3",
        "Custom Containers Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Spatial Anchors does not run customer container workloads; deprecated November 2024; not_applicable",
    ),
    (
        "PV-3",
        "Custom VM Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Spatial Anchors PaaS does not expose VM image customization; deprecated November 2024; not_applicable",
    ),
    (
        "DP-5",
        "Data at Rest Encryption Using CMK",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Spatial Anchors does not support CMK; deprecated November 2024; not_applicable",
    ),
    (
        "DP-4",
        "Data at Rest Encryption Using Platform Keys",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: platform-enforced, enabled by default, not customer-configurable; deprecated November 2024",
    ),
    (
        "DP-3",
        "Data in Transit Encryption",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: platform-enforced, enabled by default, not customer-configurable; deprecated November 2024",
    ),
    (
        "DP-2",
        "Data Leakage/Loss Prevention",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Spatial Anchors does not support DLP controls; deprecated November 2024; not_applicable",
    ),
    (
        "LT-1",
        "Microsoft Defender for Service / Product Offering",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; no Microsoft Defender plan for Spatial Anchors; deprecated November 2024; not_applicable",
    ),
    (
        "NS-2",
        "Disable Public Network Access",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Spatial Anchors does not support disabling public network access; deprecated November 2024; not_applicable",
    ),
    (
        "ES-1",
        "EDR Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; EDR targets customer-managed endpoints; PaaS Spatial Anchors not applicable; deprecated November 2024; not_applicable",
    ),
    (
        "DP-6",
        "Key Management in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Spatial Anchors does not use Key Vault for key management; deprecated November 2024; not_applicable",
    ),
    (
        "PA-1",
        "Local Admin Accounts",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Spatial Anchors PaaS does not expose local admin accounts; deprecated November 2024; not_applicable",
    ),
    # None row — asb_control_id preserved as empty string
    (
        "",
        "Local Authentication Methods for Data Plane Access",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Local auth keys supported for Spatial Anchors SDK; source xlsx row has missing ASB control ID; deprecated November 2024",
    ),
    (
        "IM-1",
        "Local Authentication Methods for Data Plane Access",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Local auth (account key) supported alongside AAD; customers should prefer AAD; deprecated November 2024",
    ),
    (
        "IM-3",
        "Managed Identities",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Spatial Anchors does not support Managed Identity assignment; deprecated November 2024; not_applicable",
    ),
    (
        "BR-1",
        "Service Native Backup Capability",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Spatial Anchors does not support native backup; deprecated November 2024; not_applicable",
    ),
    (
        "NS-1",
        "Network Security Group Support",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Spatial Anchors does not support VNet/NSG integration; deprecated November 2024; not_applicable",
    ),
    (
        "NS-2",
        "Azure Private Link",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Spatial Anchors does not support Private Link; deprecated November 2024; not_applicable",
    ),
    (
        "LT-4",
        "Azure Resource Logs",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Spatial Anchors does not emit Azure Monitor resource logs; deprecated November 2024; not_applicable",
    ),
    (
        "DP-1",
        "Sensitive Data Discovery and Classification",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Spatial Anchors does not support data discovery or classification; deprecated November 2024; not_applicable",
    ),
    (
        "IM-3",
        "Service Principals",
        "True",
        "False",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Service Principals supported for Spatial Anchors auth via AAD app registration; deprecated November 2024",
    ),
    (
        "NS-1",
        "Virtual Network Integration",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Spatial Anchors does not support VNet integration; deprecated November 2024; not_applicable",
    ),
    (
        "PV-5",
        "Vulnerability Assessment using Microsoft Defender",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Vulnerability Assessment targets customer VMs; PaaS Spatial Anchors service not applicable; deprecated November 2024; not_applicable",
    ),
]

TRUSTEDHARDWAREIM_ROWS = [
    (
        "IM-1",
        "Azure AD Authentication Required for Data Plane Access",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; THIM service provides unauthenticated public cache of hardware attestation collateral (TPM/SEV-SNP certificates); public endpoint by design — no AAD auth required or applicable; not_applicable",
    ),
    (
        "AM-5",
        "Microsoft Defender for Cloud - Adaptive Application Controls",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "IM-8",
        "Service Credential and Secrets Support Integration and Storage in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "ES-2",
        "Anti-Malware Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "ES-3",
        "Anti-Malware Solution Health Monitoring",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "PV-3",
        "Azure Automation State Configuration",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "PV-6",
        "Azure Automation Update Management",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "BR-1",
        "Azure Backup",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "PV-3",
        "Azure Policy Guest Configuration Agent",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "AM-2",
        "Azure Policy Support",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "PA-7",
        "Azure RBAC for Data Plane",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "DP-7",
        "Certificate Management in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "IM-7",
        "Conditional Access for Data Plane",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "PA-8",
        "Customer Lockbox",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "PV-3",
        "Custom Containers Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "PV-3",
        "Custom VM Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "DP-5",
        "Data at Rest Encryption Using CMK",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "DP-4",
        "Data at Rest Encryption Using Platform Keys",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "DP-3",
        "Data in Transit Encryption",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "DP-2",
        "Data Leakage/Loss Prevention",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "LT-1",
        "Microsoft Defender for Service / Product Offering",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "NS-2",
        "Disable Public Network Access",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "ES-1",
        "EDR Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "DP-6",
        "Key Management in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "PA-1",
        "Local Admin Accounts",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "IM-1",
        "Local Authentication Methods for Data Plane Access",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "IM-3",
        "Managed Identities",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "BR-1",
        "Service Native Backup Capability",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "NS-1",
        "Network Security Group Support",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "NS-2",
        "Azure Private Link",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "LT-4",
        "Azure Resource Logs",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "DP-1",
        "Sensitive Data Discovery and Classification",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "IM-3",
        "Service Principals",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
    (
        "NS-1",
        "Virtual Network Integration",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False in MCSB v3 baseline; THIM is a public platform endpoint; no VNet integration concept; not_applicable",
    ),
    (
        "PV-5",
        "Vulnerability Assessment using Microsoft Defender",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; THIM is a transparent platform caching service for hardware attestation certificates; fully Microsoft-managed; no customer-configurable controls; not_applicable",
    ),
]

UNIVERSALPRINT_ROWS = [
    (
        "IM-1",
        "Azure AD Authentication Required for Data Plane Access",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Universal Print enforces Entra ID authentication for all print operations; AAD required for printer registration and print job submission",
    ),
    (
        "AM-5",
        "Microsoft Defender for Cloud - Adaptive Application Controls",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Adaptive Application Controls targets VMs; Universal Print is a SaaS service; not_applicable",
    ),
    (
        "IM-8",
        "Service Credential and Secrets Support Integration and Storage in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Universal Print uses AAD authentication; no service credentials requiring Key Vault storage; not_applicable",
    ),
    (
        "ES-2",
        "Anti-Malware Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Universal Print is a SaaS service; anti-malware not applicable at service resource level; not_applicable",
    ),
    (
        "ES-3",
        "Anti-Malware Solution Health Monitoring",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; anti-malware health monitoring targets customer VMs; SaaS Universal Print not applicable",
    ),
    (
        "PV-3",
        "Azure Automation State Configuration",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Azure Automation DSC targets customer VMs; SaaS Universal Print not applicable",
    ),
    (
        "PV-6",
        "Azure Automation Update Management",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Update Management targets customer VMs; SaaS Universal Print not applicable",
    ),
    (
        "BR-1",
        "Azure Backup",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Universal Print is a SaaS service with no customer data requiring Azure Backup; not_applicable",
    ),
    (
        "PV-3",
        "Azure Policy Guest Configuration Agent",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Guest Configuration targets VMs; SaaS Universal Print not applicable",
    ),
    (
        "AM-2",
        "Azure Policy Support",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Universal Print does not support Azure Policy assignment or resource tagging in standard deployment; not_applicable",
    ),
    (
        "PA-7",
        "Azure RBAC for Data Plane",
        "True",
        "False",
        "implemented",
        "Microsoft.Print/printers/*/read (RBAC assignment)",
        "LIVE-DIRECT: Universal Print uses Azure RBAC for printer management; Printer Administrator built-in role; check RBAC assignments on printer resources",
    ),
    (
        "DP-7",
        "Certificate Management in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Universal Print does not use Key Vault for certificate management; not_applicable",
    ),
    (
        "IM-7",
        "Conditional Access for Data Plane",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Conditional Access evaluates Entra ID sign-in sessions; Universal Print uses Microsoft Graph API with app permissions, not interactive sign-in; not_applicable",
    ),
    (
        "PA-8",
        "Customer Lockbox",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Universal Print not in Customer Lockbox supported service list; not_applicable",
    ),
    (
        "PV-3",
        "Custom Containers Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Universal Print does not run customer container workloads; not_applicable",
    ),
    (
        "PV-3",
        "Custom VM Images",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Universal Print SaaS does not expose VM image customization; not_applicable",
    ),
    (
        "DP-5",
        "Data at Rest Encryption Using CMK",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: Universal Print supports Customer Key for Microsoft 365 encryption; platform-enforced CMK applied via Microsoft 365 compliance admin center",
    ),
    (
        "DP-4",
        "Data at Rest Encryption Using Platform Keys",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: platform-enforced, enabled by default, not customer-configurable",
    ),
    (
        "DP-3",
        "Data in Transit Encryption",
        "True",
        "True",
        "implemented",
        "N/A — microsoft_managed PASS static",
        "microsoft_managed: platform-enforced, enabled by default, not customer-configurable",
    ),
    (
        "DP-2",
        "Data Leakage/Loss Prevention",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Universal Print does not support DLP controls at the service level; not_applicable",
    ),
    (
        "LT-1",
        "Microsoft Defender for Service / Product Offering",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; no Microsoft Defender plan for Universal Print; not_applicable",
    ),
    (
        "NS-2",
        "Disable Public Network Access",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Universal Print does not expose public IP endpoints; not_applicable",
    ),
    (
        "ES-1",
        "EDR Solution",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; EDR targets customer-managed endpoints; SaaS Universal Print not applicable",
    ),
    (
        "DP-6",
        "Key Management in Azure Key Vault",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Universal Print does not use Key Vault for key management; not_applicable",
    ),
    (
        "PA-1",
        "Local Admin Accounts",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Universal Print SaaS does not expose local admin accounts; not_applicable",
    ),
    (
        "IM-1",
        "Local Authentication Methods for Data Plane Access",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Universal Print requires Entra ID authentication; local authentication methods not supported; not_applicable",
    ),
    (
        "IM-3",
        "Managed Identities",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Universal Print does not support Managed Identity assignment to the service; not_applicable",
    ),
    (
        "BR-1",
        "Service Native Backup Capability",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Universal Print does not support native backup; print queue data is transient; not_applicable",
    ),
    (
        "NS-1",
        "Network Security Group Support",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Universal Print does not have customer-controlled instances or public IP endpoints; service is Microsoft-managed SaaS; traffic rules not configurable; not_applicable",
    ),
    (
        "NS-2",
        "Azure Private Link",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Universal Print does not have public IP endpoints; Private Link not applicable to this SaaS service; not_applicable",
    ),
    (
        "LT-4",
        "Azure Resource Logs",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False in MCSB v3 baseline; Universal Print does not support Azure Monitor diagnostic logs; print audit logs available via Microsoft 365 compliance portal (Purview Audit) not via Azure DiagSettings; not_applicable",
    ),
    (
        "DP-1",
        "Sensitive Data Discovery and Classification",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Universal Print does not support data discovery or classification; not_applicable",
    ),
    (
        "IM-3",
        "Service Principals",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Universal Print does not support Service Principal authentication to the service; not_applicable",
    ),
    (
        "NS-1",
        "Virtual Network Integration",
        "False",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=False; Universal Print is a SaaS service; no VNet integration; not_applicable",
    ),
    (
        "PV-5",
        "Vulnerability Assessment using Microsoft Defender",
        "Not Applicable",
        "Not Applicable",
        "still_not_applicable",
        "",
        "feature_supported=Not Applicable; Vulnerability Assessment targets customer VMs; SaaS Universal Print not applicable",
    ),
]

# ── service manifest ──────────────────────────────────────────────────────────
SERVICES = [
    ("addds", ADDDS_ROWS),
    ("attestation", ATTESTATION_ROWS),
    ("botservice", BOTSERVICE_ROWS),
    ("cloudshell", CLOUDSHELL_ROWS),
    ("intelligentrecommendations", INTELLIGENTRECOMMENDATIONS_ROWS),
    ("spatialanchors", SPATIALANCHORS_ROWS),
    ("trustedhardwareim", TRUSTEDHARDWAREIM_ROWS),
    ("universalprint", UNIVERSALPRINT_ROWS),
]

VALID_VERDICTS = {
    "implemented",
    "now_applicable_native",
    "upgraded_implemented",
    "still_not_applicable",
    "conditional",
    "not_applicable_paas",
    "not_applicable_arm",
}


def write_csv(slug: str, rows: list) -> Path:
    """Write a rechecked_controls CSV for the given service slug."""
    out_path = OUTPUT_DIR / f"{slug}_rechecked_controls.csv"
    with open(out_path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh, quoting=csv.QUOTE_ALL)
        writer.writerow(HEADER)
        for row in rows:
            (
                asb_control_id,
                feature_name,
                supported,
                enabled_default,
                verdict,
                azure_api_property,
                notes,
            ) = row
            writer.writerow(
                [
                    asb_control_id,
                    feature_name,
                    supported,
                    enabled_default,
                    verdict,        # status_2025 == verdict_2025
                    verdict,        # verdict_2025
                    azure_api_property,
                    "",             # script_module
                    "",             # script_function
                    notes,
                ]
            )
    return out_path


def validate_csv(path: Path, expected_rows: int) -> list[str]:
    """Return a list of error strings; empty list means PASS."""
    errors = []
    with open(path, newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        # Check header
        if reader.fieldnames != HEADER:
            errors.append(f"BAD HEADER: {reader.fieldnames}")
        rows = list(reader)
        # Row count
        if len(rows) != expected_rows:
            errors.append(f"ROW COUNT: expected {expected_rows}, got {len(rows)}")
        for i, r in enumerate(rows, start=2):
            # No empty verdict
            if not r["verdict_2025"].strip():
                errors.append(f"row {i}: empty verdict_2025")
            # Valid verdict
            elif r["verdict_2025"] not in VALID_VERDICTS:
                errors.append(f"row {i}: invalid verdict '{r['verdict_2025']}'")
            # No empty notes
            if not r["notes"].strip():
                errors.append(f"row {i}: empty notes")
            # status == verdict
            if r["status_2025"] != r["verdict_2025"]:
                errors.append(
                    f"row {i}: status_2025 '{r['status_2025']}' != verdict_2025 '{r['verdict_2025']}'"
                )
            # script fields must be empty
            if r["script_module"] != "":
                errors.append(f"row {i}: script_module not empty: '{r['script_module']}'")
            if r["script_function"] != "":
                errors.append(f"row {i}: script_function not empty: '{r['script_function']}'")
    return errors


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    all_ok = True
    for slug, rows in SERVICES:
        path = write_csv(slug, rows)
        errors = validate_csv(path, expected_rows=len(rows))
        status = "PASS" if not errors else "FAIL"
        if errors:
            all_ok = False
        print(f"{status} {path.name} ({len(rows)} rows)")
        for e in errors:
            print(f"      ERROR: {e}")

    print()
    if all_ok:
        print("All 8 CSVs generated and validated successfully.")
    else:
        print("Validation FAILED — see errors above.")
        sys.exit(1)


if __name__ == "__main__":
    main()
