"""Phase 47 — PA domain CSV generation (Automation, Customer Lockbox, Lighthouse)."""
import csv
import pathlib

OUT = pathlib.Path("data/outputs")

HEADER = [
    "asb_control_id", "feature_name", "feature_supported_original",
    "feature_enabled_by_default_original", "status_2025", "verdict_2025",
    "azure_api_property", "script_module", "script_function", "notes",
]

AUTOMATION_ROWS = [
    ("IM-1","Azure AD Authentication Required for Data Plane Access","True","True","implemented","implemented","N/A — microsoft_managed PASS static","","","microsoft_managed: Azure Automation enforces AAD authentication for runbook execution and management API; always enabled; platform-enforced"),
    ("AM-5","Microsoft Defender for Cloud - Adaptive Application Controls","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; no compute workloads in Automation Account; Adaptive Application Controls applies to VMs not PaaS services; not_applicable"),
    ("IM-8","Service Credential and Secrets Support Integration and Storage in Azure Key Vault","True","True","implemented","implemented","N/A — microsoft_managed PASS static","","","microsoft_managed: Azure Automation Account natively integrates Key Vault for runbook credential and secret management; KV-backed secure assets available by default; platform-enforced"),
    ("ES-2","Anti-Malware Solution","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Automation Account is PaaS; Hybrid Worker VMs are customer-managed and not in scope here; anti-malware not applicable at Account level"),
    ("ES-3","Anti-Malware Solution Health Monitoring","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; PaaS Account level; Hybrid Worker VM health is customer responsibility; not_applicable"),
    ("PV-3","Azure Automation State Configuration","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Automation IS the State Configuration service; the Account cannot configure itself via DSC; not_applicable"),
    ("PV-6","Azure Automation Update Management","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Automation IS the Update Management service; no concept of updating the Account itself via Update Management; not_applicable"),
    ("BR-1","Azure Backup","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Azure Automation Account configuration (runbooks, schedules, connections) not covered by Azure Backup; use source control integration for runbook versioning; not_applicable"),
    ("PV-3","Azure Policy Guest Configuration Agent","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; PaaS Account; no VM guest agent concept; not_applicable"),
    ("AM-2","Azure Policy Support","True","True","implemented","implemented","N/A — microsoft_managed PASS static","","","microsoft_managed: Azure Policy governance applies to Automation Accounts via Azure Resource Manager; policy assignments enforced platform-side"),
    ("PA-7","Azure RBAC for Data Plane","True","True","implemented","implemented","N/A — microsoft_managed PASS static","","","microsoft_managed: Azure Automation enforces RBAC for runbook and job operations; built-in roles: Automation Operator, Automation Job Operator, Automation Runbook Operator; platform-enforced access control"),
    ("DP-7","Certificate Management in Azure Key Vault","True","False","implemented","implemented","automationAccount.properties.encryption.keyVaultProperties.keyUri","","","LIVE-DIRECT: Azure Automation supports certificate assets referencing Key Vault for runbook authentication; check encryption keyVaultProperties for active KV reference"),
    ("IM-7","Conditional Access for Data Plane","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Automation runbook execution uses MI or Run As account; no separate Conditional Access evaluation point for data plane operations; not_applicable"),
    ("PA-8","Customer Lockbox","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Azure Automation not in Customer Lockbox supported service list; not_applicable"),
    ("PV-3","Custom Containers Images","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; PaaS Account; no container image management; not_applicable"),
    ("PV-3","Custom VM Images","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; PaaS Account; no VM image management at Account level; not_applicable"),
    ("DP-5","Data at Rest Encryption Using CMK","True","False","implemented","implemented","automationAccount.properties.encryption.keySource","","","LIVE-DIRECT: Azure Automation Account supports CMK for encrypting stored assets; check properties.encryption.keySource == Microsoft.Keyvault"),
    ("DP-4","Data at Rest Encryption Using Platform Keys","True","True","implemented","implemented","N/A — microsoft_managed PASS static","","","microsoft_managed: Azure Automation Account encrypts all stored data (runbooks, credentials, connection assets) at rest using Microsoft-managed keys by default; platform-enforced"),
    ("DP-3","Data in Transit Encryption","True","True","implemented","implemented","N/A — microsoft_managed PASS static","","","microsoft_managed: Azure Automation enforces TLS 1.2+ for all API and webhook traffic; platform-enforced"),
    ("DP-2","Data Leakage/Loss Prevention","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Automation is an orchestration service; DLP concept not applicable to runbook execution infrastructure; not_applicable"),
    ("LT-1","Microsoft Defender for Service / Product Offering","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; no dedicated Microsoft Defender plan for Azure Automation Account service; Defender for Servers covers Hybrid Worker VMs separately; not_applicable at Account level"),
    ("NS-2","Disable Public Network Access","True","False","implemented","implemented","automationAccount.properties.publicNetworkAccess","","","LIVE-DIRECT: Azure Automation Account supports disabling public network access; check properties.publicNetworkAccess == Disabled"),
    ("ES-1","EDR Solution","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; PaaS Account; no endpoint layer at Account level; Hybrid Worker VMs are customer responsibility; not_applicable"),
    ("DP-6","Key Management in Azure Key Vault","True","False","implemented","implemented","automationAccount.properties.encryption.keyVaultProperties.keyUri","","","LIVE-DIRECT: Azure Automation supports CMK key rotation via Key Vault; check properties.encryption.keyVaultProperties.keyUri for active KV reference"),
    ("PA-1","Local Admin Accounts","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Automation Account is PaaS; no local admin account concept; not_applicable"),
    ("IM-1","Local Authentication Methods for Data Plane Access","True","False","implemented","implemented","N/A — LIVE→behavior check","","","LIVE-DIRECT: Azure Automation supports local credential assets (stored username/password); customers should prefer Managed Identity over stored credentials; review credential asset usage for least-privilege compliance"),
    ("IM-3","Managed Identities","True","True","implemented","implemented","N/A — microsoft_managed PASS static","","","microsoft_managed: Azure Automation Account supports system-assigned and user-assigned managed identities; MI replaces deprecated Run As account for runbook authentication; platform-enforced"),
    ("BR-1","Service Native Backup Capability","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Automation Account runbooks and configuration not backed up by Azure Backup; source control integration recommended for versioning; not_applicable"),
    ("NS-1","Network Security Group Support","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Automation Account is PaaS; NSG applies to Hybrid Worker VMs (customer-managed), not the Account endpoint; not_applicable at Account level"),
    ("NS-2","Azure Private Link","True","False","implemented","implemented","automationAccount.properties.privateEndpointConnections","","","LIVE-DIRECT: Azure Automation Account supports private endpoints for webhook and management API traffic; check properties.privateEndpointConnections length > 0"),
    ("LT-4","Azure Resource Logs","True","False","implemented","implemented","DiagnosticSettings(automationAccount.id).logs","","","LIVE-DIRECT: Azure Automation emits diagnostic logs (JobLogs, JobStreams, DscNodeStatus, AuditEvent); check DiagnosticSettings for at least one log category enabled"),
    ("DP-1","Sensitive Data Discovery and Classification","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; data classification is customer responsibility on data processed by runbooks; Azure Automation does not perform discovery on runbook inputs/outputs; not_applicable"),
    ("IM-3","Service Principals","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Azure Automation Run As account (service principal) deprecated October 2023; Microsoft recommends migrating to Managed Identity; still_not_applicable for current implementations"),
    ("NS-1","Virtual Network Integration","True","False","implemented","implemented","automationAccount.properties.privateEndpointConnections","","","LIVE-DIRECT: Azure Automation integrates with customer VNet via Hybrid Runbook Worker Group; check hybridRunbookWorkerGroup configured for private network execution; private endpoints also supported for PaaS control plane"),
    ("PV-5","Vulnerability Assessment using Microsoft Defender","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; PaaS Account; no compute or OS layer to scan at Account level; not_applicable"),
]

CUSTOMERLOCKBOX_ROWS = [
    ("IM-1","Azure AD Authentication Required for Data Plane Access","True","True","implemented","implemented","N/A — microsoft_managed PASS static","","","microsoft_managed: Customer Lockbox portal enforces AAD authentication for approving and denying Microsoft support access requests; always enabled; platform-enforced"),
    ("AM-5","Microsoft Defender for Cloud - Adaptive Application Controls","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Customer Lockbox is a portal-based approval workflow; no compute workloads; not_applicable"),
    ("IM-8","Service Credential and Secrets Support Integration and Storage in Azure Key Vault","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox approval workflow does not use or integrate Key Vault; no credential management concept in Lockbox; not_applicable"),
    ("ES-2","Anti-Malware Solution","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; portal-based approval service; no compute or OS layer; not_applicable"),
    ("ES-3","Anti-Malware Solution Health Monitoring","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; portal-only service; no compute to monitor; not_applicable"),
    ("PV-3","Azure Automation State Configuration","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Customer Lockbox is a portal service; no VM or DSC concept; not_applicable"),
    ("PV-6","Azure Automation Update Management","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; portal service; no OS patching concept; not_applicable"),
    ("BR-1","Azure Backup","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Customer Lockbox is a subscription-level portal service; no data store to back up; not_applicable"),
    ("PV-3","Azure Policy Guest Configuration Agent","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; portal service; no VM guest agent concept; not_applicable"),
    ("AM-2","Azure Policy Support","False","Not Applicable","now_applicable_native","now_applicable_native","subscription.policy.assignments[name='customer-lockbox']","","","now_applicable_native: MCSB v3 baseline recorded False but Azure Policy built-in definition 'Customer Lockbox should be enabled for your subscription' (Policy ID: ca6d0de3-aca0-4a46-9f73-69a31e1fa3e6) now exists for auditing Lockbox enablement; script check deferred to later phase"),
    ("PA-7","Azure RBAC for Data Plane","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox approval requires Global Administrator or Account Administrator role; no granular RBAC data plane for Lockbox approval workflow; not_applicable"),
    ("DP-7","Certificate Management in Azure Key Vault","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox is an approval workflow; no certificate or key management concept; not_applicable"),
    ("IM-7","Conditional Access for Data Plane","False","Not Applicable","now_applicable_native","now_applicable_native","conditionalAccessPolicy.conditions.applications.includeApplications[AzurePortal]","","","now_applicable_native: MCSB v3 baseline recorded False but Conditional Access policies can gate Azure portal access — the only path for Lockbox approval and denial operations; CA policies applied to Azure portal (app ID 00000006-0000-0ff1-ce00-000000000000) effectively enforce CA for all Lockbox operations; script check deferred to later phase"),
    ("PA-8","Customer Lockbox","True","False","implemented","implemented","subscription.properties.features.customerLockbox","","","LIVE-DIRECT: Customer Lockbox IS the PA-8 control; check Lockbox is enabled at subscription level; approval workflow enforces least-privilege for Microsoft support access requests; verify customerLockbox feature enabled via Security Center API"),
    ("PV-3","Custom Containers Images","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; portal service; no container concept; not_applicable"),
    ("PV-3","Custom VM Images","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; portal service; no VM image concept; not_applicable"),
    ("DP-5","Data at Rest Encryption Using CMK","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Customer Lockbox does not store customer data requiring at-rest encryption; approval metadata stored by Microsoft; not_applicable"),
    ("DP-4","Data at Rest Encryption Using Platform Keys","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Customer Lockbox does not store customer data; no customer-controlled at-rest encryption concept; not_applicable"),
    ("DP-3","Data in Transit Encryption","False","Not Applicable","now_applicable_native","now_applicable_native","N/A — microsoft_managed PASS static","","","now_applicable_native: MCSB v3 baseline recorded False but Customer Lockbox is accessed exclusively via Azure portal which enforces TLS 1.2 for all traffic; microsoft_managed TLS enforcement applies to all Lockbox approval and denial operations; script check deferred to later phase"),
    ("DP-2","Data Leakage/Loss Prevention","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox approval workflow does not process or store customer data subject to DLP controls; not_applicable"),
    ("LT-1","Microsoft Defender for Service / Product Offering","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; no Microsoft Defender plan for Customer Lockbox service; not_applicable"),
    ("NS-2","Disable Public Network Access","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox is a subscription-level portal service; no private endpoint or public access toggle concept; portal-only access; not_applicable"),
    ("ES-1","EDR Solution","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; portal service; no endpoint layer; not_applicable"),
    ("DP-6","Key Management in Azure Key Vault","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox does not manage encryption keys; no KV integration concept; not_applicable"),
    ("PA-1","Local Admin Accounts","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox requires Global Administrator role for approval; no local admin account concept; not_applicable"),
    ("IM-1","Local Authentication Methods for Data Plane Access","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox portal access requires AAD authentication; no local auth alternative; not_applicable"),
    ("IM-3","Managed Identities","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox is a subscription-level portal workflow; no managed identity concept for approval operations; not_applicable"),
    ("BR-1","Service Native Backup Capability","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Customer Lockbox has no data store; backup concept not applicable; not_applicable"),
    ("NS-1","Network Security Group Support","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox is a subscription-level portal service; no VNet or NSG concept; not_applicable"),
    ("NS-2","Azure Private Link","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox accessed via Azure portal only; Private Link not applicable; not_applicable"),
    ("LT-4","Azure Resource Logs","False","Not Applicable","now_applicable_native","now_applicable_native","ActivityLog.filter(resourceType='Microsoft.CustomerLockbox')","","","now_applicable_native: MCSB v3 baseline recorded False but Customer Lockbox access requests (approvals and denials) are now captured as Activity Log events under Microsoft.CustomerLockbox resource type; auditable via Azure Monitor Activity Log; script check deferred to later phase"),
    ("DP-1","Sensitive Data Discovery and Classification","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox does not perform data discovery or classification; not_applicable"),
    ("IM-3","Service Principals","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox operations use Global Admin AAD credentials, not service principals; not_applicable"),
    ("NS-1","Virtual Network Integration","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Customer Lockbox is not deployed into customer VNet; portal-only service; not_applicable"),
    ("PV-5","Vulnerability Assessment using Microsoft Defender","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; portal service; no compute or OS layer to scan; not_applicable"),
]

LIGHTHOUSE_ROWS = [
    ("IM-1","Azure AD Authentication Required for Data Plane Access","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Lighthouse is a cross-tenant delegation framework; AAD auth handled by managing tenant identity provider, not Lighthouse service itself; not_applicable at Lighthouse level"),
    ("AM-5","Microsoft Defender for Cloud - Adaptive Application Controls","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Lighthouse is a control-plane delegation service; no compute workloads; not_applicable"),
    ("IM-8","Service Credential and Secrets Support Integration and Storage in Azure Key Vault","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Lighthouse delegation model uses AAD principal IDs; no credential or secret management concept; not_applicable"),
    ("ES-2","Anti-Malware Solution","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; control-plane service; no compute or OS layer; not_applicable"),
    ("ES-3","Anti-Malware Solution Health Monitoring","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; control-plane service; no compute to monitor; not_applicable"),
    ("PV-3","Azure Automation State Configuration","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Lighthouse has no VM or DSC concept; not_applicable"),
    ("PV-6","Azure Automation Update Management","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; control-plane service; no OS patching concept; not_applicable"),
    ("BR-1","Azure Backup","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Lighthouse is a delegation metadata service; no backup data store; not_applicable"),
    ("PV-3","Azure Policy Guest Configuration Agent","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; control-plane service; no VM guest agent; not_applicable"),
    ("AM-2","Azure Policy Support","True","False","implemented","implemented","registrationDefinition.properties.authorizations[roleDefinitionId]","","","LIVE-DIRECT: Azure Lighthouse enables cross-tenant Azure Policy delegation; check registrationDefinition.properties.authorizations contains Policy Contributor or Policy Insights Data Reader role for MSP; enables policy assignment and audit across customer tenant"),
    ("PA-7","Azure RBAC for Data Plane","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Lighthouse IS a RBAC delegation mechanism; PA-7 control does not apply recursively to Lighthouse itself; delegated roles tracked in registrationDefinitions; not_applicable as a separate control"),
    ("DP-7","Certificate Management in Azure Key Vault","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Lighthouse delegation uses AAD principal IDs; no certificate management; not_applicable"),
    ("IM-7","Conditional Access for Data Plane","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Lighthouse delegation is ARM-based; CA evaluates identity in managing tenant, not Lighthouse data plane; not_applicable"),
    ("PA-8","Customer Lockbox","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Lighthouse is a delegation framework; Customer Lockbox concept not applicable; not_applicable"),
    ("PV-3","Custom Containers Images","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; control-plane service; no container workloads; not_applicable"),
    ("PV-3","Custom VM Images","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; control-plane service; no VM image management; not_applicable"),
    ("DP-5","Data at Rest Encryption Using CMK","False","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=False; Azure Lighthouse stores only delegation metadata; no customer data requiring CMK; not_applicable"),
    ("DP-4","Data at Rest Encryption Using Platform Keys","True","True","implemented","implemented","N/A — microsoft_managed PASS static","","","microsoft_managed: Azure Lighthouse delegation metadata and registration definitions encrypted at rest using Microsoft-managed keys; platform-enforced"),
    ("DP-3","Data in Transit Encryption","True","True","implemented","implemented","N/A — microsoft_managed PASS static","","","microsoft_managed: All Azure Lighthouse ARM management API calls enforce TLS 1.2+; delegation operations use HTTPS exclusively; platform-enforced"),
    ("DP-2","Data Leakage/Loss Prevention","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Lighthouse stores delegation configuration only; DLP not applicable; not_applicable"),
    ("LT-1","Microsoft Defender for Service / Product Offering","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Lighthouse is a control-plane delegation framework; no Defender product offering for Lighthouse; not_applicable"),
    ("NS-2","Disable Public Network Access","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Lighthouse is accessed via ARM REST API; no public network access toggle; not_applicable"),
    ("ES-1","EDR Solution","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; control-plane service; no endpoint layer; not_applicable"),
    ("DP-6","Key Management in Azure Key Vault","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Lighthouse has no encryption key management; not_applicable"),
    ("PA-1","Local Admin Accounts","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Lighthouse delegation uses AAD principals; no local admin concept; not_applicable"),
    ("IM-1","Local Authentication Methods for Data Plane Access","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Lighthouse uses AAD principal-based delegation; no local auth method concept; not_applicable"),
    ("IM-3","Managed Identities","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Lighthouse delegation uses user, group, or service principal IDs from managing tenant; managed identity concept not applicable to delegation model"),
    ("BR-1","Service Native Backup Capability","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Lighthouse delegation configuration stored in ARM; backup concept not applicable; customer should version registrationDefinitions via IaC; not_applicable"),
    ("NS-1","Network Security Group Support","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Lighthouse is a pure control-plane service; no VNet or NSG concept; not_applicable"),
    ("NS-2","Azure Private Link","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Lighthouse accessed via ARM API; Private Link not applicable to Lighthouse delegation; not_applicable"),
    ("LT-4","Azure Resource Logs","False","Not Applicable","now_applicable_native","now_applicable_native","ActivityLog.filter(operationName='Microsoft.ManagedServices/*')","","","now_applicable_native: MCSB v3 baseline recorded False but Azure Lighthouse now generates Activity Log events for all delegation operations (registration assignments, access grants) under Microsoft.ManagedServices namespace; auditable via Azure Monitor Activity Log queries; script check deferred to later phase"),
    ("DP-1","Sensitive Data Discovery and Classification","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Lighthouse stores only delegation configuration metadata; data classification not applicable; not_applicable"),
    ("IM-3","Service Principals","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Lighthouse delegation model uses principal IDs from managing tenant; no separate service principal management at Lighthouse level; not_applicable"),
    ("NS-1","Virtual Network Integration","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; Azure Lighthouse is a control-plane delegation service; VNet integration not applicable; not_applicable"),
    ("PV-5","Vulnerability Assessment using Microsoft Defender","Not Applicable","Not Applicable","still_not_applicable","still_not_applicable","","","","feature_supported=Not Applicable; control-plane service; no compute or OS layer to scan; not_applicable"),
]

def write_csv(path, rows):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(HEADER)
        w.writerows(rows)
    print(f"Written: {path} ({len(rows)} rows)")

write_csv(OUT / "automation_rechecked_controls_v2.csv", AUTOMATION_ROWS)
write_csv(OUT / "customerlockbox_rechecked_controls_v2.csv", CUSTOMERLOCKBOX_ROWS)
write_csv(OUT / "lighthouse_rechecked_controls_v2.csv", LIGHTHOUSE_ROWS)
